version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: if [ ! -d node_modules ]; then npm ci; fi
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
